FROM buildpack-deps:<%= variant || "bookworm" %>

ENV LANG=C.UTF-8
ENV RUBY_VERSION=<%= version || "2.4.10" %>

# Using https://github.com/rbenv/ruby-build to install OpenSSL 1.1 in <%= variant || "bookworm" %>
ADD --chmod=755 https://raw.githubusercontent.com/rbenv/ruby-build/master/bin/ruby-build /usr/local/bin/ruby-build
ADD https://raw.githubusercontent.com/rbenv/ruby-build/master/share/ruby-build/$RUBY_VERSION /tmp/ruby.build

RUN set -eux; \
    mkdir -p /usr/local/etc; \
    { \
      echo 'install: --no-document'; \
      echo 'update: --no-document'; \
    } >> /usr/local/etc/gemrc; \
    ruby-build /tmp/ruby.build /usr/local; \
    rm -rf /tmp/*; \
    ruby --version; \
    gem update --system <%= rubygems || "3.3.27" %> --no-doc

# The unpleasant part : https://wiki.archlinux.org/title/Ruby#Configuration
# https://felipec.wordpress.com/2023/02/27/fixing-ruby-gems-installation-part-2/
ENV GEM_HOME="$(gem env user_gemhome)"
ENV PATH=$GEM_HOME/bin:$GEM_HOME/gems/bin:$PATH

# Then, you should `bundle config set --local path '~/some/path' in your app folder
# https://wiki.archlinux.org/title/Ruby#Bundler

CMD [ "irb" ]
